# available colors (names are case-insensitive):
#   black, red, green, yellow, blue, magenta, cyan, white
# every color may have up to 3 modifiers:
#   bold, underline, bright(or intense)
[colors]
color_term = "ansi"
overdue = "bright red"
threshold = "red"
top = "bright red"
important = "white"
done = "bright black"
today = "bright yellow"
soon = "white"
old = "bright black"
# default_fg = "white"

[ranges]
soon = 0
important = ""
old = "1y"

[global]
creation_date_auto = true
clean_subject = "all"
auto_hide_columns = true
fields="done,pri,due"
strict_mode=true


[syntax]
enabled = true
tag_color = "cyan"
hashtag_color = "cyan"
project_color = "bright magenta"
context_color = "blue"

